### PR TITLE
Add home page in react

### PR DESCRIPTION
**Pull request by EdithBenvenuto**
* Add a provitional navbar
* Remove some files we aren't using (reportWebVitals.js, setupTests.js...)
* Add a images folder

### CODE REVIEW

**Review by mcollins42 — COMMENTED** [review]
I think something went wrong with the PR here. This is showing every file in the repo modified. I'm guessing there was a bad base for main. I would suggest:

1. go to your local git repo
2. `git checkout main` to switch to the main branch 
3. `git pull origin` to get up to date with the GitHub main branch
4. `git checkout react-mainPage`
5. `git merge main`
6. `git push origin`

That should update this branch and PR. If that doesn't work, then I would go back to the main branch (make a copy of your changed files first) and start a new branch just for the react home page and copy your changes into that new branch, push it and create a new PR.

**Comment by EdithBenvenuto** [comment]
@mcollins42 I merged main into my branch, does it work?

**Review by mcollins42 — COMMENTED** [review]
It still shows all of the files as if they are brand new (61 files) total. Let me see if I can fix it.

**Comment by mcollins42** [comment]
Closing this because the code was added in #11.

**Pull request closed without merging**
