### PR TITLE
Add all drugs page

### PR DESCRIPTION
**Pull request by mcollins42**
This is a second try at a branch and PR for just the code Edith added in https://github.com/mcollins42/sps-sm21-team-19/pull/10.

 I had to do a little merging on:
* src/main/react-webapp/src/App.js 
* src/main/react-webapp/src/components/Home.js

Please make sure those look correct.

### CODE REVIEW

**Review by EdithBenvenuto — APPROVED** [review]
I checked and the code is the same

**Comment by GMarsh0218** [comment]
I just tried to compile, there was a missing return statement on home.js and Home.css is missing

**Comment by EdithBenvenuto** [comment]
Thanks Garrett! I didn't notice

**Comment by EdithBenvenuto** [comment]
I'll add home.css

**Comment by EdithBenvenuto** [comment]
I added home.css, Navbar.js and images, also added a link to bootstrap in index.html

**Pull request merged**
